<?php

use Dompdf\Dompdf;

class Report {
    use Controller;

    public function rentalIncome(string $a = '', string $b = '', string $c = ''): void
    {
        // Prepare request and response objects
        $request = new JSONRequest;
        $response = new JSONResponse;

        // Prepare data for model query
        $d = [
            'id' => UserMiddleware::getUser()['id'],
            'from' => $request->get('from'),
            'to' => $request->get('to')
        ];

        // Fetch rental information and income data
        $rental = new RentalServiceModel;
        $data = [
            'info' => $rental->getRentalService($d['id'])[0],
            'income' => $rental->GetMonthlyIncome($d['id'], $d['from'], $d['to'])
        ];

        // Initialize variables for the PDF generation
        $id = uniqid();
        $serviceFeeRate = 10 / 100;
        $name = $data['info']->name;
        $address = $data['info']->address;
        $companyName = "Wanderlust";
        $reportTitle = "Monthly Income Report for {$name}";
        $reportDate = date("Y-m-d");

        // Start output buffering
        ob_start();
        ?>

        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <title>Income Report</title>
            <style>
                body {
                    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                    margin: 40px;
                    color: #333;
                    line-height: 1.6;
                }
                h1, h2 {
                    text-align: center;
                    color: #026;
                }
                table {
                    width: 100%;
                    margin-top: 20px;
                    border-collapse: collapse;
                    border-spacing: 0;
                    box-shadow: 0 2px 15px rgba(0, 0, 0, 0.1);
                }
                th, td {
                    border: 1px solid #ddd;
                    padding: 12px 15px;
                    text-align: left;
                }
                th {
                    background-color: #f8f8f8;
                    color: #333;
                }
                tr:nth-child(even) {
                    background-color: #f2f2f2;
                }
                p {
                    text-align: center;
                }
                .footer {
                    margin-top: 20px;
                    text-align: center;
                    font-size: 0.85em;
                    color: #666;
                }
                .footer a {
                    color: #333;
                }
            </style>
        </head>
        <body>
            <h1><?= $companyName ?></h1>
            <h2><?= $reportTitle ?><br><?= $reportDate ?></h2>
            <p><strong>Name:</strong> <?= $name ?><br><strong>Address:</strong> <?= $address ?></p>
            <table>
                <thead>
                    <tr>
                        <th>Month</th>
                        <th>Income (Rs.)</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($data['income'] as $monthlyIncome): ?>
                        <tr>
                            <td><?= $monthlyIncome->Month ?></td>
                            <td><?= number_format($monthlyIncome->MonthlyIncome, 2) ?></td>
                        </tr>
                    <?php endforeach; ?>
                    <?php
                    // Calculate totals and service fees
                    $totalIncome = array_sum(array_column($data['income'], 'MonthlyIncome'));
                    $serviceFee = $totalIncome * $serviceFeeRate;
                    $netIncome = $totalIncome - $serviceFee;
                    ?>
                    <tr><td><strong>Total</strong></td><td><strong>Rs.<?= number_format($totalIncome, 2) ?></strong></td></tr>
                    <tr><td><strong>Service Fee</strong></td><td><strong>Rs.<?= number_format($serviceFee, 2) ?></strong></td></tr>
                    <tr><td><strong>Net Income</strong></td><td><strong>Rs.<?= number_format($netIncome, 2) ?></strong></td></tr>
                </tbody>
            </table>
            <div class="footer">
                <p>This report was generated by the system on <?= $reportDate ?></p>
                <p>Verify at: <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/reports/income_report_<?= $id ?>.pdf">https://<?= $_SERVER['HTTP_HOST'] ?>/reports/income_report_<?= $id ?>.pdf</a></p>
            </div>
        </body>
        </html>

        <?php
        $html = ob_get_clean();

        // Create and configure DOMPDF instance
        $dompdf = new Dompdf();
        $dompdf->loadHtml($html);
        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();

        // Save and send the PDF file
        $output = $dompdf->output();
        file_put_contents("reports/income_report_{$id}.pdf", $output);
        $response->data(['report' => "income_report_{$id}.pdf"])->send();
    }


    public function GetEquipmentRentalCountByRentalService(string $a = '', string $b = '', string $c = ''): void
    {
        // Prepare request and response objects
        $request = new JSONRequest;
        $response = new JSONResponse;

        // Fetch rental service ID

        $data = $request->getAll();


        $data["id"] = UserMiddleware::getUser()['id'];





        // Fetch equipment rental count
        $rental = new RentalServiceModel;
        $data['equipment'] = $rental->GetEquipmentRentalCountByRentalService($data);
        $data['info'] = $rental->getRentalService($data['id'])[0];

        // Initialize variables for the PDF generation
        $id = uniqid();

        $companyName = "Wanderlust";
        $reportTitle = "Equipment Rental Count Report for {$data['info']->name}";
        $reportDate = date("Y-m-d");

        // Start output buffering
        ob_start();

        // show($data['equipment']);
        ?>
         <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <title>Income Report</title>
            <style>
                body {
                    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                    margin: 40px;
                    color: #333;
                    line-height: 1.6;
                }
                h1, h2 {
                    text-align: center;
                    color: #026;
                }
                table {
                    width: 100%;
                    margin-top: 20px;
                    border-collapse: collapse;
                    border-spacing: 0;
                    box-shadow: 0 2px 15px rgba(0, 0, 0, 0.1);
                }
                th, td {
                    border: 1px solid #ddd;
                    padding: 12px 15px;
                    text-align: left;
                }
                th {
                    background-color: #f8f8f8;
                    color: #333;
                }
                tr:nth-child(even) {
                    background-color: #f2f2f2;
                }
                p {
                    text-align: center;
                }
                .footer {
                    margin-top: 20px;
                    text-align: center;
                    font-size: 0.85em;
                    color: #666;
                }
                .footer a {
                    color: #333;
                }
            </style>
        </head>
        <body>
            <h1><?= $companyName ?></h1>
            <h2><?= $reportTitle ?><br><?= $reportDate ?></h2>
            <p><strong>Name:</strong> <?= $data['info']->name ?><br><strong>Address:</strong> <?= $data['info']->address ?></p>
            <table>
                <thead>
                    <tr>
                        <th>Id </th>
                        <th>Equipment</th>
                        <th>Rental Count</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($data['equipment'] as $equipment): ?>
                        <tr>
                            <td><?= $equipment->equipment_id ?></td>
                            <td><?= $equipment->equipment_name ?></td>
                            <td><?= $equipment->rental_count ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <div class="footer">
                <p>This report was generated by the system on <?= $reportDate ?></p>
                <p>Verify at: <a href="https://<?= $_SERVER['HTTP_HOST'] ?>/reports/equipment_report_<?= $id ?>.pdf">https://<?= $_SERVER['HTTP_HOST'] ?>/reports/equipment_report_<?= $id ?>.pdf</a></p>
            </div>
        </body>
        </html>
        <?php

        $html = ob_get_clean();

        // Create and configure DOMPDF instance
        $dompdf = new Dompdf();
        $dompdf->loadHtml($html);
        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();

        // Save and send the PDF file
        $output = $dompdf->output();
        file_put_contents("reports/equipment_report_{$id}.pdf", $output);
        $response->data(['report' => "equipment_report_{$id}.pdf"])->send();




        
    }

}

?>
